version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: infra/docker/fastapi/Dockerfile
    ports:
    - "9000:8000"
    environment:
    - PYTHONPATH=/app/src
    - ARXIV_MCP_ENABLE=true
    - ARXIV_STORAGE_PATH=/app/arxiv-papers
    volumes:
    - ./src:/app/src
    networks:
    - papers-network

  chainlit:
    build:
      context: .
      dockerfile: infra/docker/chainlit/Dockerfile
    ports:
    - "8000:8000"
    environment:
    - PAPERS_API_BASE=http://fastapi:8000
    - PYTHONPATH=/app/src
    volumes:
    - ./src:/app/src
    depends_on:
    - fastapi
    networks:
    - papers-network

networks:
  papers-network:
    driver: bridge
