from src.graphs.message_routing import create_message_routing_graph
from src.graphs.corrective_rag import create_corrective_rag_graph
from src.graphs.content_enhancement import create_content_enhancement_graph


process_message_graph = create_message_routing_graph()
corrective_rag_graph = create_corrective_rag_graph()
content_enhancement_graph = create_content_enhancement_graph()
